### ISSUE TITLE
Multi orientation videos

### ISSUE THREAD

**Issue by DREXJAOL** [dev-labs-bg/swift-video-generator#12]
Hi, I really like your project, thanks for sharing. Im working on a private project where I would like to make the videocomposition landscape for all videos if just one of the videos selected for merge is landscape. and then rotate the rest of the portrait oriented videos accordingly while having black spaces on each side. Will you please point me in the right direction in regards of makeing an addition to you great project. I think this particually part is missing in most video merge projects I've seen...

**Comment by tgeorgieva** [comment]
I'm sorry, I don't really have the time right now to research this and I haven't done it, so I can't really tell you what to do off the top of my head. 

But I've seen some Stack Overflow answers that explain how to. You can create a method that rotates all portrait videos to landscape before you use the generator to merge them instead of trying to rewrite the existing code since that would be more difficult. That's the first thing that comes to mind right now.
