### ISSUE TITLE
Black frames at end of merged video

### ISSUE THREAD

**Issue by darnfish** [dev-labs-bg/swift-video-generator#18]
Hey there,

I'm trying to merge several video files that are around one second long. It works fine, but at the end of each merged video there is a couple black frames.

There's also an issue where if there is no audio track the VideoGenerator throws an error.

Thanks for your work on this project!

**Comment by tgeorgieva** [comment]
Hello.

I haven't tried using the merger with such short videos, but when I'm generating a video from images and audio, I always get an error if the video is bellow 3 seconds. That's why I've hardcoded such a minimum duration in the video generator. I don't have anything like that set up for the video merging feature, but it might be the system's way of protecting itself, adding those few extra frames at the end of your videos. Just my first thoughts on the issue. 

Yes, I haven't intended for the VideoGenerator to be used on videos without audio. An oversight I will rectify but I'm trying to decide which of the requested features to implement and how to make them all fit. Everyone seems to have very specific requirements for their projects and trying to cram them all together in one library is making it a little haphazard and messy. 

Thank you for your interest.
