### ISSUE TITLE
Big size videos not reversing and application crashed

### ISSUE THREAD

**Issue by dhaneshgosai** [dev-labs-bg/swift-video-generator#19]
Hello Team,

I am checking demo attached with this repo and I have replaced default video with my video and try to replace video its crashing app.

Please check it once.

Thanks

**Comment by tgeorgieva** [comment]
Hello. 

Thank you for the feedback. But to be able to trace the problem, I'll need more information.

What was the video? Size? Orientation? Quality? You need to add those details because as you've reported it right now I can't do anything. There's nothing for me to check.

Also, keep in mind that an iPhone/iPad has just so much processing power. If you load a 100MB photo in UIImageView, it will crash, too.

What was the error you got when it crashed? Was it a memory error or something else? Fill in the details and I'll check it out first chance I get.

**Comment by chetanPuwar21** [comment]
> Hello Team,
> 
> I am checking demo attached with this repo and I have replaced default video with my video and try to replace video its crashing app.
> 
> Please check it once.
> 
> Thanks

Hii... are you there?

Your Crashing app issue is solved?

**Comment by chetanPuwar21** [comment]
> Hello.
> 
> Thank you for the feedback. But to be able to trace the problem, I'll need more information.
> 
> What was the video? Size? Orientation? Quality? You need to add those details because as you've reported it right now I can't do anything. There's nothing for me to check.
> 
> Also, keep in mind that an iPhone/iPad has just so much processing power. If you load a 100MB photo in UIImageView, it will crash, too.
> 
> What was the error you got when it crashed? Was it a memory error or something else? Fill in the details and I'll check it out first chance I get.

Hii...
 
I think this is memory issue. due to "copyNextSampleBuffer()"

**Comment by tgeorgieva** [comment]
@chetanPuwar21  Hello. 
First, let me start with this - this device (iPhone or iPad) has memory limitations. If you're trying to convert an HD video or something equally big, there is nothing to be done. I can refactor the code all day and it'll still crash.

That's why I asked for more information. But since you've tested it and seem to know where the issue is, feel free to work on it and create a merge request. I will review when I have the time and test to see its limitations.

I don't think I will have the time to look into this before the Holidays, however. And without more details, there's nothing to look into.

**Comment by chetanPuwar21** [comment]
> @chetanPuwar21 Hello.
> First, let me start with this - this device (iPhone or iPad) has memory limitations. If you're trying to convert an HD video or something equally big, there is nothing to be done. I can refactor the code all day and it'll still crash.
> 
> That's why I asked for more information. But since you've tested it and seem to know where the issue is, feel free to work on it and create a merge request. I will review when I have the time and test to see its limitations.
> 
> I don't think I will have the time to look into this before the Holidays, however. And without more details, there's nothing to look into.

Thanks for reply.

my video size is only 30mb. this is not too big.

**Comment by chetanPuwar21** [comment]
> @chetanPuwar21 Hello.
> First, let me start with this - this device (iPhone or iPad) has memory limitations. If you're trying to convert an HD video or something equally big, there is nothing to be done. I can refactor the code all day and it'll still crash.
> 
> That's why I asked for more information. But since you've tested it and seem to know where the issue is, feel free to work on it and create a merge request. I will review when I have the time and test to see its limitations.
> 
> I don't think I will have the time to look into this before the Holidays, however. And without more details, there's nothing to look into.

are you solved this issue?
