### ISSUE TITLE
generate() should not use hardcoded filename "test.m4v" for video output

### ISSUE THREAD

**Issue by mog96** [dev-labs-bg/swift-video-generator#36]
Using generate() to create multiple videos in sequence I get the following error:
> “test.m4v” couldn’t be moved to “Documents” because an item with the same name already exists.

**Comment by tgeorgieva** [comment]
@mog96 It doesn't use a hardcoded filename. If you look at the code you'll see why it's needed. If you have a better idea for how to save a file without a name, do tell.

I will see why this could be happening, if I can reproduce it. But if you're reporting a bug give detailed information about it so the one you're expecting to fix it can do so. Printing out the error for me will do little if it's a file system bug since I can't test on your device and it might not happen on mine.

Also, a little advice - next time you think you know what I should and shouldn't do, please, fork the repo, fix the issues you see and create a merge request.

**Comment by mog96** [comment]
Hi Teddy,

I apologize for being so vague.

The solution I had in mind when I posted this was to take an output file name/URL as a parameter to generate(), such that the client of your code is able to avoid name collisions. The issue was occurring when I was using generate() more than once in sequence, and so it seemed to me that the hardcoded file name was causing the issue. Perhaps I did not read through the code carefully enough.

I would gladly fork and create a pull request but unfortunately the single still image-based videos I was getting were ending up blacked out when I merged them with other videos. This was the case for most other implementations I found online as well. I have since found a solution that does not have this issue, which I am currently using: https://github.com/Tulakshana/Composer

I greatly appreciate the work you guys are doing.

Thank you,
Mateo

**Comment by tgeorgieva** [comment]
@mog96 
On the first point, about the name collision - I need the file "test.m4v" because it's the temporary file created by merging the array of images. After that I check if there is any audio to be added and if there is, I use this temporary file as a medium to add the audio into (no other way to generate the video). If there isn't I rename the file form "test.m4v" to the custom name the user has specified (or "singleMovie" if not specified). And "test.m4v" is the easiest name to use because, hopefully, that wouldn't be the real name of any video :D 

I don't know of any other ways to directly attach the audio to the images without a medium temporary video. If there is I can take a look and find the time to test it and rewrite the generator if necessary. 

I never thought about a use case with a sequence of videos and so have never tested it. Always figured generating would be one at a time. Do you give the next video a different name,, always, to avoid deleting the old ones?

I think there is a bug in the file system because I've been testing and the "FileManager.default.removeItem" can't seem to delete the "test.m4v" video after the creation is finished (the way I first designed it to do). I will check and see if Swift 4 and iOS 12 don't have any issues with deleting files like this and fix the issue so it works as expected. I think that could be what's causing the issue. I will fix and deploy a new version to see if that is, indeed, the problem.

I'm sorry to hear about the blacked out images. I don't know why that could be happening... This was after a generate() and then merge()? 

Happy to hear you found a solution, though. Hope it's working great. 

I will fix the issue with the missing file deletion, see if that helps :)
