### ISSUE TITLE
How to split video inside for loop?

### ISSUE THREAD

**Issue by takasurazeem** [dev-labs-bg/swift-video-generator#52]
```chunks = [[0, 10], [11, 18]]
            for chunk in chunks {
                VideoGenerator.current.splitVideo(withURL: url!, atStartTime: Double(chunk[0]), andEndTime: Double(chunk[1]), success: { (url) in
                    self.videoArray.append(url)
                    print("chunk: videoArray: \(self.videoArray)")
                    print("chunk: videoArray count: \(self.videoArray.count)")
                }) { (err) in
                    print("Error: \(err)")
                }
            }

**Comment by tgeorgieva** [comment]
@takasurazeem I don't understand what you want to do or what the problem is that you're having. This isn't SO and I'm not here to do code reviews. I can't alter the library to cater to every specific project's needs. This library is already far removed from what I had in mind for it anyway.

If there is an issue with the library, please provide detailed description and examples and I'll check it when I can or decide if it's a feature I want to add.

**Comment by takasurazeem** [comment]
VideoGenerator.fileName = Helper.uniqueFilename(filename: "chunks_video")
I have set the file name to be a concatenation of chunks_video and UUID string but everytime the loop executes it generates same name!

**Comment by tgeorgieva** [comment]
@takasurazeem This doesn't seem like a bug no my end, more a problem with how or where you set the name. I'm guessing the old file overrides because you always give the same name for every next video. I suggest going over your code and thinking about how and when you should be setting the video name.
