### ISSUE TITLE
Issue with Generating video - Last black images is showing

### ISSUE THREAD

**Issue by testingflexsin** [dev-labs-bg/swift-video-generator#54]
Hi, I am creating the video from multiple images. So i am facing issue i.e. sometimes i found black frame in last seconds of video that progress of images is not completed. If you found any reference for reproducing this bug , please ping me here
Seeking for your positive response.

**Comment by testingflexsin** [comment]
Please update.

**Comment by tgeorgieva** [comment]
@testingflexsin Unless you provide a specific and detailed report of the bug there's nothing I can do about it. I honestly can't understand what the issue is from what you've written. 

What exactly is the issue? Was it during generating? Merging? Splitting a video?

What does " that progress of images is not completed" mean? Are you checking the video before the generating is complete? Is it okay when it's complete?

Unless you describe what exactly the issue is, I can't "updte" anything.
