### ISSUE TITLE
Issue in creating video from multiple frames

### ISSUE THREAD

**Issue by testingflexsin** [dev-labs-bg/swift-video-generator#56]
Hi Team , 

Please find attached code and video where we are creating the video from multiple frames. 

So we are using your code to create video from multiple frames. So you can see in video that we are getting 52 frames and we would need 60 frames to make the complete video. It happens most of times but not always. So I am sharing the sample as well. Please suggest what I am doing wrong. I am creating video from front camera not back camera. 

Video Link :- https://tinyurl.com/y5z7352t

Code Link :- https://tinyurl.com/yxmo9d5s

Please let me know if you need any reference.

**Comment by SteliyanH** [comment]
@testingflexsin,
First of all, we can't run your code because it is missing an essential file - AppDelegate.swift. Because of this we can't investigate what is happening and suggest/apply possible fixes. If possible provide the missing file and afterward we will again look into the issue.

**Comment by tgeorgieva** [comment]
@testingflexsin Hello. 

I looked at your video and I couldn't get much in the way of explanation. 

As I saw in the video, you seem to be getting some errors with your images. "Couldn't load image...." etc. Maybe you should check out those first? There are at least 6 images that seem to be unable to load?

Also, you're saying you need 60 frames, that the issue happens only sometimes but you're not explaining the issue or the result fully. What is wrong with the video when the issue occurs? Are there missing images? If so, I still suggest you check why you can't load all of them and if the images you're getting the error for are the same ones missing from the finished video.

If not, provide further detailed explanation about the issue, when it occurs and what the finished video's lacking when compared to the one generated when the issue didn't occur.

**Comment by testingflexsin** [comment]
@tgeorgieva  
Please check this video link :-  https://tinyurl.com/y5ytp5w4. 

You can watch this video that we are not getting full frames(between 7th sec to 8th sec in video) during generating a video. It happens sometimes not every times. Please help me out from this issue. 

Please let me know what you are required from my side. 

Thanks.

**Comment by tgeorgieva** [comment]
@testingflexsin As I wrote in my last comment, I can't help you without a properly detailed issue. I'm not here to do a code review of your project. So I need to know what you've done to debug the issue and how did you reach the conclusion the bug is from the library. Recently, someone opened an issue they thought had to do with my library. It turned out the person in question just didn't know how to declare a button properly. To avoid wasting time, again, I will need more details if I am to believe this issue is coming from my library. Especially with the word "sometimes" used in the description.

You had images that couldn't load in the code sample/video you send. Are those solved? 

Under what conditions does the generation fail? Because if the video is "sometimes" rendered correctly, chances are it's not my library that's the problem. Maybe your input or the workflow you're using to create the video is changing?
