### ISSUE TITLE
when i pass more then 15 images for make a video that time application crash and display below error please suggest me how to solve this issue

### ISSUE THREAD

**Issue by Bhavesh5291** [dev-labs-bg/swift-video-generator#8]
[GatekeeperXPC] Connection to assetsd was interrupted or assetsd died
Message from debugger: Terminated due to memory issue

**Comment by tgeorgieva** [comment]
I'm sorry, I don't really have time to look into this now and I can't promise when I will. But this is obviously a memory issue, so it might be due to the image sizes. You can try resizing the images to make them smaller, see if that's what's causing the leak. That's the only thing I can suggest without testing it out myself but I've done up to 10 images and had no problem with memory leaks. 
I'll leave this open for when I have the time to look further into it.

**Comment by tgeorgieva** [comment]
Hi. I looked into this issue and fixed it. I was using a lot of image resizing and scaling logic and it was causing the app to crash with memory warnings. It should be fine now.
